<a href="https://colab.research.google.com/github/shahdelmasry12/AI-Machine-Learning-MSP/blob/main/Numpy%26Pandas_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import pandas as pd

**Task-1: Using NumPy, write a simple Python script that does the following:**

1. Create a one-dimensional array with numeric values.
2. Perform a basic arithmetic operation on the array (such as addition or multiplication).
3. Select specific elements from the array using indexing or slicing.
4. Reshape the array into a two-dimensional form.
5. Generate random numbers using NumPy.

In [35]:
#create array
array1=np.array([2,5,7,8,9,4])
array2=np.array([6,7,1,2,8,3])
print("array1 ",array1)
print("array2 ",array2)

array1  [2 5 7 8 9 4]
array2  [6 7 1 2 8 3]

In [36]:
#basic operations
sum_arrays=array1+array2
multiplication_array1=array1*2
multiplication_array2=array2*3
print("sum of arrays ",sum_arrays)
print("multiplication of array1 ",multiplication_array1)
print("multiplication of array2 ",multiplication_array2)

sum of arrays  [ 8 12  8 10 17  7]
multiplication of array1  [ 4 10 14 16 18  8]
multiplication of array2  [18 21  3  6 24  9]

In [37]:
#indexing // slicing
print(array1[0])
print(array2[-1])
print(multiplication_array1[::2])

2
3
[ 4 14 18]

In [38]:
#reshape
d= np.arange(8).reshape(2,4)
d

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
#random numbers
randint_array= np.random.randint(0,10,2)
print("randint array ",randint_array)

randint array  [8 1]

**Task-2: Using Pandas, write a Python script that does the following:**

1. Create a DataFrame containing student information.
2. Display basic information about the data.
3. Filter the data based on a condition.
4. Add a new column based on a logical condition.
5. Calculate a simple aggregate value from one column.**

In [40]:
#Create a DataFrame containing student information.
data= {
'Name': ['Ali', 'Shahd', 'Roaa', 'Heba','Salma','Noha'],
'Age': [18,21,19,24,25,26],
'Score': [70,60,80,90,95,85]
}
df=pd.DataFrame(data)
df

    Name  Age  Score
0    Ali   18     70
1  Shahd   21     60
2   Roaa   19     80
3   Heba   24     90
4  Salma   25     95
5   Noha   26     85

In [41]:
#Display basic information about the data.
print(df.shape)
print(30*"*")
print(df.info())
print(30*"*")
print(df.describe())
print(30*"*")
print(df.head())
print(30*"*")
print(df.tail())

(6, 3)
******************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Score   6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes
None
******************************
             Age      Score
count   6.000000   6.000000
mean   22.166667  80.000000
std     3.311596  13.038405
min    18.000000  60.000000
25%    19.500000  72.500000
50%    22.500000  82.500000
75%    24.750000  88.750000
max    26.000000  95.000000
******************************
    Name  Age  Score
0    Ali   18     70
1  Shahd   21     60
2   Roaa   19     80
3   Heba   24     90
4  Salma   25     95
******************************
    Name  Age  Score
1  Shahd   21     60
2   Roaa   19     80
3   Heba   24     90
4  Salma   25     95
5   Noha   26     85

In [42]:
#Filter the data based on a condition.
age_filter= df[df['Age']>=20]
score_filter= df[df['Score']<70]
print(age_filter)
print(30*"*")
print(score_filter)

    Name  Age  Score
1  Shahd   21     60
3   Heba   24     90
4  Salma   25     95
5   Noha   26     85
******************************
    Name  Age  Score
1  Shahd   21     60

In [43]:
#Add a new column based on a logical condition.
df['pass']=df['Score']>60
df

    Name  Age  Score   pass
0    Ali   18     70   True
1  Shahd   21     60  False
2   Roaa   19     80   True
3   Heba   24     90   True
4  Salma   25     95   True
5   Noha   26     85   True

In [44]:
#Calculate a simple aggregate value from one column
print("The Mean of Age = ",df['Age'].mean())
print(30*"*")
print("The Sum of Age = ",df['Age'].sum())
print(30*"*")
print("The Min of Age = ",df['Age'].min())
print(30*"*")
print("The Median of Age = ",df['Age'].median())
print(30*"*")
print("The Max of Age = ",df['Age'].max())

The Mean of Age =  22.166666666666668
******************************
The Sum of Age =  133
******************************
The Min of Age =  18
******************************
The Median of Age =  22.5
******************************
The Max of Age =  26

**Task-3: Write a Python script that:**

1. Creates two NumPy arrays for height and weight.
2. Stores them in a Pandas DataFrame.
3. Displays basic statistics about the data.
4. Uses NumPy to calculate BMI (Body Mass Index) and adds it as a new column.
5. Filters and displays rows where BMI is above 25.

In [45]:
#Creates two NumPy arrays for height and weight
height=np.array([170,160,150,155,165,180,190,195,175,185,157,170])
weight=np.array([77,61,50,56,60,75,82,85,90,40,67,60])
print("Length of height ",len(height))
print("Length of weight ",len(weight))

Length of height  12
Length of weight  12

In [46]:
#Stores them in a Pandas DataFrame.
dict={
    'Height':height,
    'Weight':weight
}
df=pd.DataFrame(dict)
df

    Height  Weight
0      170      77
1      160      61
2      150      50
3      155      56
4      165      60
5      180      75
6      190      82
7      195      85
8      175      90
9      185      40
10     157      67
11     170      60

In [47]:
#Displays basic statistics about the data (Height)
print("The Mean of Height ",int(df['Height'].mean()))
print(30*"*")
print("The Median of Height ",int(df['Height'].median()))
print(30*"*")
print("The Mode of Height ",df['Height'].mode())
print(30*"*")
print("The count of Height ",df['Height'].count())
print(30*"*")
print("The Max of Height ",df['Height'].max())
print(30*"*")
print("The Min of Height ",df['Height'].min())
print(30*"*")
print("The Sum of Height ",df['Height'].sum())
print(30*"*")
print("The Std of Height ",df['Height'].std())
print(30*"*")
print("The Variance of Height ",df['Height'].var())
print(30*"*")
print()

The Mean of Height  171
******************************
The Median of Height  170
******************************
The Mode of Height  0    170
Name: Height, dtype: int64
******************************
The count of Height  12
******************************
The Max of Height  195
******************************
The Min of Height  150
******************************
The Sum of Height  2052
******************************
The Std of Height  14.403282454168059
******************************
The Variance of Height  207.45454545454547
******************************

In [48]:
#Displays basic statistics about the data (Weight)
print("The Mean of Weight ",int(df['Weight'].mean()))
print(30*"*")
print("The Median of Weight ",int(df['Weight'].median()))
print(30*"*")
print("The Mode of Weight ",df['Weight'].mode())
print(30*"*")
print("The count of Weight ",df['Weight'].count())
print(30*"*")
print("The Max of Weight ",df['Weight'].max())
print(30*"*")
print("The Min of Weight ",df['Weight'].min())
print(30*"*")
print("The Sum of Weight ",df['Weight'].sum())
print(30*"*")
print("The Std of Weight ",df['Weight'].std())
print(30*"*")
print("The Variance of Weight ",df['Weight'].var())
print(30*"*")
print()

The Mean of Weight  66
******************************
The Median of Weight  64
******************************
The Mode of Weight  0    60
Name: Weight, dtype: int64
******************************
The count of Weight  12
******************************
The Max of Weight  90
******************************
The Min of Weight  40
******************************
The Sum of Weight  803
******************************
The Std of Weight  15.12047578215672
******************************
The Variance of Weight  228.62878787878788
******************************

In [49]:
#Uses NumPy to calculate BMI (Body Mass Index) and adds it as a new column.
BMI=df['Weight']/np.power(df['Height']/100,2)
df['BMI']=BMI
df

    Height  Weight        BMI
0      170      77  26.643599
1      160      61  23.828125
2      150      50  22.222222
3      155      56  23.309053
4      165      60  22.038567
5      180      75  23.148148
6      190      82  22.714681
7      195      85  22.353715
8      175      90  29.387755
9      185      40  11.687363
10     157      67  27.181630
11     170      60  20.761246

In [50]:
#Filters and displays rows where BMI is above 25.
df[df['BMI']>25]

    Height  Weight        BMI
0      170      77  26.643599
8      175      90  29.387755
10     157      67  27.181630